<?php

namespace Database\Seeders;

use App\Models\country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class countrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

$array=[    
["shortName"=>'AF', "Name"=>'Afghanistan',"phoneCode"=> 93],    
["shortName"=>'AL', "Name"=>'Albania', "phoneCode"=>355],
["shortName"=>'DZ', "Name"=>'Algeria', "phoneCode"=>213],
["shortName"=>'AS', "Name"=>'American Samoa', "phoneCode"=>1684],
["shortName"=>'AD', "Name"=>'Andorra', "phoneCode"=>376],
["shortName"=>'AO', "Name"=>'Angola', "phoneCode"=>244],
["shortName"=>'AI', "Name"=>'Anguilla', "phoneCode"=>1264],
["shortName"=>'AQ', "Name"=>'Antarctica', "phoneCode"=>0],
["shortName"=>'AG', "Name"=>'Antigua And Barbuda',"phoneCode"=> 1268],
["shortName"=>'AR', "Name"=>'Argentina', "phoneCode"=>54],
["shortName"=>'AM', "Name"=>'Armenia', "phoneCode"=>374],
["shortName"=>'AW', "Name"=>'Aruba',"phoneCode"=> 297],
["shortName"=>'AU', "Name"=>'Australia',"phoneCode"=> 61],
["shortName"=>'AT', "Name"=>'Austria',"phoneCode"=> 43],
["shortName"=>'AZ', "Name"=>'Azerbaijan',"phoneCode"=> 994],
["shortName"=>'BS', "Name"=>'Bahamas The', "phoneCode"=>1242],
["shortName"=>'BH', "Name"=>'Bahrain',"phoneCode"=> 973],
["shortName"=>'BD', "Name"=>'Bangladesh',"phoneCode"=> 880],
["shortName"=>'BB', "Name"=>'Barbados', "phoneCode"=>1246],
["shortName"=>'BY', "Name"=>'Belarus',"phoneCode"=> 375],
["shortName"=>'BE', "Name"=>'Belgium',"phoneCode"=> 32],
["shortName"=>'BZ', "Name"=>'Belize', "phoneCode"=>501],
["shortName"=>'BJ', "Name"=>'Benin',"phoneCode"=> 229],
["shortName"=>'BM', "Name"=>'Bermuda',"phoneCode"=> 1441],
["shortName"=>'BT', "Name"=>'Bhutan',"phoneCode"=> 975],
["shortName"=>'BO', "Name"=>'Bolivia',"phoneCode"=> 591],
["shortName"=>'BA', "Name"=>'Bosnia and Herzegovina',"phoneCode"=> 387],
["shortName"=>'BW', "Name"=>'Botswana', "phoneCode"=>267],
["shortName"=>'BV', "Name"=>'Bouvet Island',"phoneCode"=> 0],
["shortName"=>'BR', "Name"=>'Brazil',"phoneCode"=> 55],
["shortName"=>'IO', "Name"=>'British Indian Ocean Territory', "phoneCode"=>246],
["shortName"=>'BN', "Name"=>'Brunei', "phoneCode"=>673],
["shortName"=>'BG', "Name"=>'Bulgaria', "phoneCode"=>359],
["shortName"=>'BF', "Name"=>'Burkina Faso',"phoneCode"=> 226],
["shortName"=>'BI', "Name"=>'Burundi', "phoneCode"=>257],
["shortName"=>'KH', "Name"=>'Cambodia',"phoneCode"=> 855],
["shortName"=>'CM', "Name"=>'Cameroon', "phoneCode"=>237],
["shortName"=>'CA', "Name"=>'Canada',"phoneCode"=> 1],
["shortName"=>'CV', "Name"=>'Cape Verde',"phoneCode"=> 238],
["shortName"=>'KY', "Name"=>'Cayman Islands', "phoneCode"=>1345],
["shortName"=>'CF', "Name"=>'Central African Republic',"phoneCode"=> 236],
["shortName"=>'TD', "Name"=>'Chad', "phoneCode"=>235],
["shortName"=>'CL', "Name"=>'Chile',"phoneCode"=> 56],
["shortName"=>'CN', "Name"=>'China',"phoneCode"=> 86],
["shortName"=>'CX', "Name"=>'Christmas Island', "phoneCode"=>61],
["shortName"=>'CC', "Name"=>'Cocos array(Keeling) Islands',"phoneCode"=> 672],
["shortName"=>'CO', "Name"=>'Colombia', "phoneCode"=>57],
["shortName"=>'KM', "Name"=>'Comoros',"phoneCode"=> 269],
["shortName"=>'CG', "Name"=>'Republic Of The Congo', "phoneCode"=>242],
["shortName"=>'CD', "Name"=>'Democratic Republic Of The Congo',"phoneCode"=> 242],
["shortName"=>'CK', "Name"=>'Cook Islands', "phoneCode"=>682],
["shortName"=>'CR', "Name"=>'Costa Rica',"phoneCode"=> 506],
["shortName"=>'CI', "Name"=>'Cote D',"phoneCode"=> 225],
["shortName"=>'HR', "Name"=>'Croatia array(Hrvatska)',"phoneCode"=> 385],
["shortName"=>'CU', "Name"=>'Cuba', "phoneCode"=>53],
["shortName"=>'CY', "Name"=>'Cyprus',"phoneCode"=> 357],
["shortName"=>'CZ', "Name"=>'Czech Republic',"phoneCode"=> 420],
["shortName"=>'DK', "Name"=>'Denmark', "phoneCode"=>45],
["shortName"=>'DJ', "Name"=>'Djibouti',"phoneCode"=> 253],
["shortName"=>'DM', "Name"=>'Dominica', "phoneCode"=>1767],
["shortName"=>'DO', "Name"=>'Dominican Republic', "phoneCode"=>1809],
["shortName"=>'TP', "Name"=>'East Timor', "phoneCode"=>670],
["shortName"=>'EC', "Name"=>'Ecuador', "phoneCode"=>593],
["shortName"=>'EG', "Name"=>'Egypt',"phoneCode"=> 20],
["shortName"=>'SV', "Name"=>'El Salvador', "phoneCode"=>503],
["shortName"=>'GQ', "Name"=>'Equatorial Guinea', "phoneCode"=>240],
["shortName"=>'ER', "Name"=>'Eritrea',"phoneCode"=> 291],
["shortName"=>'EE', "Name"=>'Estonia',"phoneCode"=> 372],
["shortName"=>'ET', "Name"=>'Ethiopia', "phoneCode"=>251],
["shortName"=>'XA', "Name"=>'External Territories of Australia',"phoneCode"=> 61],
["shortName"=>'FK', "Name"=>'Falkland Islands', "phoneCode"=>500],
["shortName"=>'FO', "Name"=>'Faroe Islands',"phoneCode"=> 298],
["shortName"=>'FJ', "Name"=>'Fiji Islands', "phoneCode"=>679],
["shortName"=>'FI', "Name"=>'Finland', "phoneCode"=>358],
["shortName"=>'FR', "Name"=>'France', "phoneCode"=>33],
["shortName"=>'GF', "Name"=>'French Guiana', "phoneCode"=>594],
["shortName"=>'PF', "Name"=>'French Polynesia',"phoneCode"=> 689],
["shortName"=>'TF', "Name"=>'French Southern Territories',"phoneCode"=> 0],
["shortName"=>'GA', "Name"=>'Gabon', "phoneCode"=>241],
["shortName"=>'GM', "Name"=>'Gambia The', "phoneCode"=>220],
["shortName"=>'GE', "Name"=>'Georgia', "phoneCode"=>995],
["shortName"=>'DE', "Name"=>'Germany',"phoneCode"=> 49],
["shortName"=>'GH', "Name"=>'Ghana', "phoneCode"=>233],
["shortName"=>'GI', "Name"=>'Gibraltar', "phoneCode"=>350],
["shortName"=>'GR', "Name"=>'Greece',"phoneCode"=> 30],
["shortName"=>'GL', "Name"=>'Greenland', "phoneCode"=>299],
["shortName"=>'GD', "Name"=>'Grenada',"phoneCode"=> 1473],
["shortName"=>'GP', "Name"=>'Guadeloupe', "phoneCode"=>590],
["shortName"=>'GU', "Name"=>'Guam', "phoneCode"=>1671],
["shortName"=>'GT', "Name"=>'Guatemala', "phoneCode"=>502],
["shortName"=>'XU', "Name"=>'Guernsey and Alderney',"phoneCode"=> 44],
["shortName"=>'GN', "Name"=>'Guinea', "phoneCode"=>224],
["shortName"=>'GW', "Name"=>'Guinea-Bissau', "phoneCode"=>245],
["shortName"=>'GY', "Name"=>'Guyana', "phoneCode"=>592],
["shortName"=>'HT', "Name"=>'Haiti',"phoneCode"=> 509],
["shortName"=>'HM', "Name"=>'Heard and McDonald Islands',"phoneCode"=> 0],
["shortName"=>'HN', "Name"=>'Honduras', "phoneCode"=>504],
["shortName"=>'HK', "Name"=>'Hong Kong S.A.R.',"phoneCode"=> 852],
["shortName"=>'HU', "Name"=>'Hungary',"phoneCode"=> 36],
["shortName"=>'IS', "Name"=>'Iceland',"phoneCode"=> 354],
["shortName"=>'IN', "Name"=>'India', "phoneCode"=>91],
["shortName"=>'ID', "Name"=>'Indonesia', "phoneCode"=>62],
["shortName"=>'IR', "Name"=>'Iran', "phoneCode"=>98],
["shortName"=>'IQ', "Name"=>'Iraq', "phoneCode"=>964],
["shortName"=>'IE', "Name"=>'Ireland', "phoneCode"=>353],
["shortName"=>'IL', "Name"=>'Israel',"phoneCode"=> 972],
["shortName"=>'IT', "Name"=>'Italy',"phoneCode"=> 39],
["shortName"=>'JM', "Name"=>'Jamaica', "phoneCode"=>1876],
["shortName"=>'JP', "Name"=>'Japan', "phoneCode"=>81],
["shortName"=>'XJ', "Name"=>'Jersey',"phoneCode"=> 44],
["shortName"=>'JO', "Name"=>'Jordan',"phoneCode"=> 962],
["shortName"=>'KZ', "Name"=>'Kazakhstan', "phoneCode"=>7],
["shortName"=>'KE', "Name"=>'Kenya',"phoneCode"=> 254],
["shortName"=>'KI', "Name"=>'Kiribati', "phoneCode"=>686],
["shortName"=>'KP', "Name"=>'Korea North', "phoneCode"=>850],
["shortName"=>'KR', "Name"=>'Korea South', "phoneCode"=>82],
["shortName"=>'KW', "Name"=>'Kuwait',"phoneCode"=> 965],
["shortName"=>'KG', "Name"=>'Kyrgyzstan',"phoneCode"=> 996],
["shortName"=>'LA', "Name"=>'Laos', "phoneCode"=>856],
["shortName"=>'LV', "Name"=>'Latvia',"phoneCode"=> 371],
["shortName"=>'LB', "Name"=>'Lebanon',"phoneCode"=> 961],
["shortName"=>'LS', "Name"=>'Lesotho',"phoneCode"=> 266],
["shortName"=>'LR', "Name"=>'Liberia',"phoneCode"=> 231],
["shortName"=>'LY', "Name"=>'Libya',"phoneCode"=> 218],
["shortName"=>'LI', "Name"=>'Liechtenstein',"phoneCode"=> 423],
["shortName"=>'LT', "Name"=>'Lithuania',"phoneCode"=> 370],
["shortName"=>'LU', "Name"=>'Luxembourg', "phoneCode"=>352],
["shortName"=>'MO', "Name"=>'Macau S.A.R.',"phoneCode"=> 853],
["shortName"=>'MK', "Name"=>'Macedonia', "phoneCode"=>389],
["shortName"=>'MG', "Name"=>'Madagascar', "phoneCode"=>261],
["shortName"=>'MW', "Name"=>'Malawi',"phoneCode"=> 265],
["shortName"=>'MY', "Name"=>'Malaysia',"phoneCode"=> 60],
["shortName"=>'MV', "Name"=>'Maldives',"phoneCode"=> 960],
["shortName"=>'ML', "Name"=>'Mali',"phoneCode"=> 223],
["shortName"=>'MT', "Name"=>'Malta',"phoneCode"=> 356],
["shortName"=>'XM', "Name"=>'Man array(Isle of)',"phoneCode"=> 44],
["shortName"=>'MH', "Name"=>'Marshall Islands', "phoneCode"=>692],
["shortName"=>'MQ', "Name"=>'Martinique', "phoneCode"=>596],
["shortName"=>'MR', "Name"=>'Mauritania',"phoneCode"=> 222],
["shortName"=>'MU', "Name"=>'Mauritius', "phoneCode"=>230],
["shortName"=>'YT', "Name"=>'Mayotte',"phoneCode"=> 269],
["shortName"=>'MX', "Name"=>'Mexico',"phoneCode"=> 52],
["shortName"=>'FM', "Name"=>'Micronesia',"phoneCode"=> 691],
["shortName"=>'MD', "Name"=>'Moldova',"phoneCode"=> 373],
["shortName"=>'MC', "Name"=>'Monaco', "phoneCode"=>377],
["shortName"=>'MN', "Name"=>'Mongolia',"phoneCode"=> 976],
["shortName"=>'MS', "Name"=>'Montserrat', "phoneCode"=>1664],
["shortName"=>'MA', "Name"=>'Morocco', "phoneCode"=>212],
["shortName"=>'MZ', "Name"=>'Mozambique',"phoneCode"=> 258],
["shortName"=>'MM', "Name"=>'Myanmar',"phoneCode"=> 95],
["shortName"=>'NA', "Name"=>'Namibia',"phoneCode"=> 264],
["shortName"=>'NR', "Name"=>'Nauru',"phoneCode"=> 674],
["shortName"=>'NP', "Name"=>'Nepal', "phoneCode"=>977],
["shortName"=>'AN', "Name"=>'Netherlands Antilles',"phoneCode"=> 599],
["shortName"=>'NL', "Name"=>'Netherlands The',"phoneCode"=> 31],
["shortName"=>'NC', "Name"=>'New Caledonia', "phoneCode"=>687],
["shortName"=>'NZ', "Name"=>'New Zealand', "phoneCode"=>64],
["shortName"=>'NI', "Name"=>'Nicaragua', "phoneCode"=>505],
["shortName"=>'NE', "Name"=>'Niger', "phoneCode"=>227],
["shortName"=>'NG', "Name"=>'Nigeria',"phoneCode"=> 234],
["shortName"=>'NU', "Name"=>'Niue', "phoneCode"=>683],
["shortName"=>'NF', "Name"=>'Norfolk Island',"phoneCode"=> 672],
["shortName"=>'MP', "Name"=>'Northern Mariana Islands', "phoneCode"=>1670],
["shortName"=>'NO', "Name"=>'Norway',"phoneCode"=> 47],
["shortName"=>'OM', "Name"=>'Oman', "phoneCode"=>968],
["shortName"=>'PK', "Name"=>'Pakistan',"phoneCode"=> 92],
["shortName"=>'PW', "Name"=>'Palau',"phoneCode"=> 680],
["shortName"=>'PS', "Name"=>'Palestinian Territory Occupied',"phoneCode"=> 970],
["shortName"=>'PA', "Name"=>'Panama', "phoneCode"=>507],
["shortName"=>'PG', "Name"=>'Papua new Guinea', "phoneCode"=>675],
["shortName"=>'PY', "Name"=>'Paraguay', "phoneCode"=>595],
["shortName"=>'PE', "Name"=>'Peru', "phoneCode"=>51],
["shortName"=>'PH', "Name"=>'Philippines', "phoneCode"=>63],
["shortName"=>'PN', "Name"=>'Pitcairn Island',"phoneCode"=> 0],
["shortName"=>'PL', "Name"=>'Poland', "phoneCode"=>48],
["shortName"=>'PT', "Name"=>'Portugal', "phoneCode"=>351],
["shortName"=>'PR', "Name"=>'Puerto Rico', "phoneCode"=>1787],
["shortName"=>'QA', "Name"=>'Qatar', "phoneCode"=>974],
["shortName"=>'RE', "Name"=>'Reunion',"phoneCode"=> 262],
["shortName"=>'RO', "Name"=>'Romania', "phoneCode"=>40],
["shortName"=>'RU', "Name"=>'Russia', "phoneCode"=>70],
["shortName"=>'RW', "Name"=>'Rwanda', "phoneCode"=>250],
["shortName"=>'SH', "Name"=>'Saint Helena',"phoneCode"=> 290],
["shortName"=>'KN', "Name"=>'Saint Kitts And Nevis',"phoneCode"=> 1869],
["shortName"=>'LC', "Name"=>'Saint Lucia', "phoneCode"=>1758],
["shortName"=>'PM', "Name"=>'Saint Pierre and Miquelon', 508],
["shortName"=>'VC', "Name"=>'Saint Vincent And The Grenadines', "phoneCode"=>1784],
["shortName"=>'WS', "Name"=>'Samoa', "phoneCode"=>684],
["shortName"=>'SM', "Name"=>'San Marino', "phoneCode"=>378],
["shortName"=>'ST', "Name"=>'Sao Tome and Principe', "phoneCode"=>239],
["shortName"=>'SA', "Name"=>'Saudi Arabia', "phoneCode"=>966],
["shortName"=>'SN', "Name"=>'Senegal', "phoneCode"=>221],
["shortName"=>'RS', "Name"=>'Serbia', "phoneCode"=>381],
["shortName"=>'SC', "Name"=>'Seychelles',"phoneCode"=> 248],
["shortName"=>'SL', "Name"=>'Sierra Leone',"phoneCode"=> 232],
["shortName"=>'SG', "Name"=>'Singapore',"phoneCode"=> 65],
["shortName"=>'SK', "Name"=>'Slovakia', "phoneCode"=>421],
["shortName"=>'SI', "Name"=>'Slovenia', "phoneCode"=>386],
["shortName"=>'XG', "Name"=>'Smaller Territories of the UK', "phoneCode"=>44],
["shortName"=>'SB', "Name"=>'Solomon Islands', "phoneCode"=>677],
["shortName"=>'SO', "Name"=>'Somalia', "phoneCode"=>252],
["shortName"=>'ZA', "Name"=>'South Africa',"phoneCode"=> 27],
["shortName"=>'GS', "Name"=>'South Georgia',"phoneCode"=> 0],
["shortName"=>'SS', "Name"=>'South Sudan',"phoneCode"=> 211],
["shortName"=>'ES', "Name"=>'Spain',"phoneCode"=> 34],
["shortName"=>'LK', "Name"=>'Sri Lanka', "phoneCode"=>94],
["shortName"=>'SD', "Name"=>'Sudan', "phoneCode"=>249],
["shortName"=>'SR', "Name"=>'Suriname', "phoneCode"=>597],
["shortName"=>'SJ', "Name"=>'Svalbard And Jan Mayen Islands',"phoneCode"=> 47],
["shortName"=>'SZ', "Name"=>'Swaziland', "phoneCode"=>268],
["shortName"=>'SE', "Name"=>'Sweden',"phoneCode"=> 46],
["shortName"=>'CH', "Name"=>'Switzerland', "phoneCode"=>41],
["shortName"=>'SY', "Name"=>'Syria',"phoneCode"=> 963],
["shortName"=>'TW', "Name"=>'Taiwan', "phoneCode"=>886],
["shortName"=>'TJ', "Name"=>'Tajikistan',"phoneCode"=> 992],
["shortName"=>'TZ', "Name"=>'Tanzania',"phoneCode"=> 255],
["shortName"=>'TH', "Name"=>'Thailand', "phoneCode"=>66],
["shortName"=>'TG', "Name"=>'Togo',"phoneCode"=> 228],
["shortName"=>'TK', "Name"=>'Tokelau',"phoneCode"=> 690],
["shortName"=>'TO', "Name"=>'Tonga',"phoneCode"=> 676],
["shortName"=>'TT', "Name"=>'Trinidad And Tobago', "phoneCode"=>1868],
["shortName"=>'TN', "Name"=>'Tunisia',"phoneCode"=> 216],
["shortName"=>'TR', "Name"=>'Turkey', "phoneCode"=>90],
["shortName"=>'TM', "Name"=>'Turkmenistan',"phoneCode"=> 7370],
["shortName"=>'TC', "Name"=>'Turks And Caicos Islands',"phoneCode"=> 1649],
["shortName"=>'TV', "Name"=>'Tuvalu', "phoneCode"=>688],
["shortName"=>'UG', "Name"=>'Uganda', "phoneCode"=>256],
["shortName"=>'UA', "Name"=>'Ukraine', "phoneCode"=>380],
["shortName"=>'AE', "Name"=>'United Arab Emirates', "phoneCode"=>971],
["shortName"=>'GB', "Name"=>'United Kingdom', "phoneCode"=>44],
["shortName"=>'US', "Name"=>'United States', "phoneCode"=>1],
["shortName"=>'UM', "Name"=>'United States Minor Outlying Islands',"phoneCode"=> 1],
["shortName"=>'UY', "Name"=>'Uruguay', "phoneCode"=>598],
["shortName"=>'UZ', "Name"=>'Uzbekistan',"phoneCode"=> 998],
["shortName"=>'VU', "Name"=>'Vanuatu',"phoneCode"=> 678],
["shortName"=>'VA', "Name"=>'Vatican City State array(Holy See)',"phoneCode"=> 39],
["shortName"=>'VE', "Name"=>'Venezuela', "phoneCode"=>58],
["shortName"=>'VN', "Name"=>'Vietnam',"phoneCode"=> 84],
["shortName"=>'VG', "Name"=>'Virgin Islands array(British)', "phoneCode"=>1284],
["shortName"=>'VI', "Name"=>'Virgin Islands array(US)', "phoneCode"=>1340],
["shortName"=>'WF', "Name"=>'Wallis And Futuna Islands',"phoneCode"=> 681],
["shortName"=>'EH', "Name"=>'Western Sahara',"phoneCode"=> 212],
["shortName"=>'YE', "Name"=>'Yemen', "phoneCode"=>967],
["shortName"=>'YU', "Name"=>'Yugoslavia', "phoneCode"=>38],
["shortName"=>'ZM', "Name"=>'Zambia',"phoneCode"=> 260],
["shortName"=>'ZW', "Name"=>'Zimbabwe', "phoneCode"=>263]

];
country::insert($array);
    }
}
